### ISSUE TITLE
Poblar la base de datos

### ISSUE THREAD

**Issue by maitecrazz** [jucansu/Proyecto-Avante#10]
Rellenar la base de datos con datos de mockup para realizar pruebas.
Lo ideal sería crear una clase java (tal vez en DAO) que poblara la BBDD utilizando los datos de un archivo de extensión XML. Dicha clase java debería poder ejecutarse en cualquier momento para repoblar la base de datos con los datos de mockup.

**Comment by jucansu** [comment]
Cierro el issue con el commit 6cf57d18d7cc2a8558cd65f068a3f88699f70e4c
